# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f6594142a9d945e36bc7ade11bf12a57635a57158bd502418b493e16f962291c7787a02df2caa4b751ce63cd1fb889ff9210f42e87cec58f564283b28134fc

test:
  secret_key_base: b95f0a02f601bbee4fd6e7f2d143948bc57f5d4f2eb5fdad34763c700517d3f72826d881fbfff5048c06da0c4232c9cd449acc205cccb869661c5b12e730ba91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
